#!/usr/bin/env bash

if [ $# -lt 2 ]; then
	echo "Usage: $0 <output.mk> <source-dir> [<source-dir> ...]"
	exit 1
fi

SRCS_MK=$1
shift
SRC_DIRS=$*

echo "# This file was generated by gensources.sh" > $SRCS_MK
echo "# DO NOT EDIT THIS FILE MANUALLY" >> $SRCS_MK

echo >> $SRCS_MK

for dir in $SRC_DIRS; do
	for file in $(\find $dir -type f \( -name '*.c' -o -name '*.cpp' -o -name '*.s' \)); do
		local without_prefix=${file#$dir/}
		echo "SRCS += $without_prefix" >> $SRCS_MK
	done
done
