#!/usr/bin/env bash

SRCS_MK=${1:-sources.mk}
shift
SRC_DIRS=$*
if [ -z "$SRC_DIRS" ]; then
	SRC_DIRS=src
fi

echo "# This file was generated by gensources.sh" > $SRCS_MK
echo "# DO NOT EDIT THIS FILE MANUALLY" >> $SRCS_MK

echo >> $SRCS_MK

for dir in $SRC_DIRS; do
	for file in $(\find $dir -type f \( -name '*.c' -o -name '*.cpp' -o -name '*.s' -o -name '*.S' \)); do
		without_prefix=${file#$dir/}
		echo "SRCS += $without_prefix" >> $SRCS_MK
	done
done
